# Support Vector Regression (SVR)

## Importing the libraries

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:

dataset = pd.read_csv('C:\\Users\\Dell\\Desktop\\python books\\ML_Udemy\\Machine Learning A-Z (Codes and Datasets)\\Assignment\\Regression\\Data.csv')

## Importing the dataset

In [10]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [11]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
y = y.reshape(len(y),1)

In [13]:
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [15]:
X_train

array([[  15.83,   41.67, 1013.39,   74.12],
       [  22.56,   62.26, 1012.11,   63.16],
       [  22.11,   59.8 , 1016.86,   70.14],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [16]:
y_train

array([[464.93],
       [445.33],
       [450.62],
       ...,
       [459.01],
       [462.72],
       [428.12]])

In [17]:
y_test

array([[431.23],
       [460.01],
       [461.14],
       ...,
       [426.86],
       [433.4 ],
       [441.94]])

In [18]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  31.63,   68.3 , 1014.8 ,   42.02],
       [  25.12,   77.95, 1009.26,   82.95],
       [  26.3 ,   59.07, 1007.84,   78.32]])

## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [20]:
print(X_train)

[[-0.51064128 -0.99638461  0.02277315  0.05081617]
 [ 0.39469717  0.62377296 -0.19308913 -0.70040581]
 [ 0.33416191  0.43020387  0.60796228 -0.22198159]
 ...
 [-0.37880893 -1.24424747  0.84406165  0.12552712]
 [-0.91824536 -1.03651478  1.54730047  0.87811995]
 [ 1.70763969  1.06756551 -1.21000282 -2.42972431]]


In [21]:
print(y_train)

[[ 0.61791213]
 [-0.53179246]
 [-0.22148954]
 ...
 [ 0.27065442]
 [ 0.48827707]
 [-1.54130348]]


## Training the SVR model on the Training set

In [22]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

## Predicting the Test set results

In [23]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  31.63,   68.3 , 1014.8 ,   42.02],
       [  25.12,   77.95, 1009.26,   82.95],
       [  26.3 ,   59.07, 1007.84,   78.32]])

In [24]:
y = regressor.predict(sc_X.transform(X_test))

In [25]:
print(y)

[-1.18306657  0.20461437  0.40667174 ... -1.19566346 -1.07806263
 -0.91481118]


In [26]:

y_pred = sc_y.inverse_transform(y.reshape(1,-1))
y_pred


array([[434.22717169, 457.88415867, 461.32880386, ..., 434.01242176,
        436.01726395, 438.80035135]])

In [27]:
y_pred.reshape(len(y_pred[0]),1)

array([[434.22717169],
       [457.88415867],
       [461.32880386],
       ...,
       [434.01242176],
       [436.01726395],
       [438.80035135]])

In [28]:
sc_y.inverse_transform(y_pred.reshape(1,-1))

array([[7857.03886634, 8260.33980913, 8319.06362939, ..., 7853.37784004,
        7887.55610401, 7935.00178143]])

In [30]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred[0]),1), y_test.reshape(len(y_test),1)),1))

[[434.23 431.23]
 [457.88 460.01]
 [461.33 461.14]
 ...
 [434.01 426.86]
 [436.02 433.4 ]
 [438.8  441.94]]


## Evaluating the Model Performance

In [31]:
len(y_pred.T)

2871

In [32]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred.T)

0.9463726762774131